### PR TITLE
Authorization

### PR DESCRIPTION
**Pull request by sajibarafatsiddiqui**
- Installed CanCanCan in your project.
- Added a role column to the users table. Remember to use a migration for this.
- A user can delete a post if it is theirs or if they have an admin role (column role has value "admin"). Use CanCanCan for this authorization.
- implemented the post deleting functionality. Add the "Delete" button to the view and make sure that only authorized users can see it.
- A user can delete a comment if it is theirs or if they have an admin role (column role has value "admin"). Use CanCanCan for this authorization.
- implemented the comment deleting functionality. Add the "Delete" button to the view and make sure that only authorized users can see it.

### CODE REVIEW

**Comment by sajibarafatsiddiqui** [comment]
image

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
Hello @sajibarafatsiddiqui 😃, 

Great work and effort you put into this project so far.

## Highlights 🚀 

There are some excellent points that you have made perfectly. Keep up! 💪

- Great job using cancan gem and adding the proper roles authorizations to the user model
- Descriptive pr and readme file
- Correct Linters
- Thank you for attaching the email which approves you're working solo for this week

However, there is always room for improvement.

> I'd like to remind you that your long hours of work are appreciated. However, the code review process is for improving your code, not criticizing it. 😄

 ## Required Changes ♻️
- [ ] Please make sure to use the cancan authorization method `load_and_authorize_resource` inside the posts controller for the destroy method to be authorized for this resource.
- [ ] Please create the `destroy` method in both posts controller and comments controller to make sure that each user is authorized to delete their own posts and comments.

_Please keep in mind that there are no inline comments because the referred files have no changes to be reviewed._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

N/A

Cheers and Happy coding!👏👨‍💻💻

Feel free to mention @MahmoudBakr23 to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by sajibarafatsiddiqui** [comment]
Please make sure to use the cancan authorization method load_and_authorize_resource inside the posts controller for the destroy method to be authorized for this resource.
@MahmoudBakr23  Where it is mentioned that I need to use above mentioned method? We have been provided tutorial here to use the ability class created inside model to do that.

**Comment by sajibarafatsiddiqui** [comment]
The delete button is now functional

**Review by Yerimah — APPROVED** [review]
# STATUS: APPROVED 🔥 

Hi @sajibarafatsiddiqui, 👋  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f474b3767725a594c47376373302f67697068792e676966


## Highlights
- Meaningful commit message 👍 
- No linter error 👍 
- Descriptive PR summary and title 👍 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
