### PR TITLE
Api

### PR DESCRIPTION
**Pull request by sajibarafatsiddiqui**
Created an API endpoint to list all posts for a user. 
http://[localhost:3000/api/users/6](http://localhost:3000/api/users/6)
image

Create an API endpoint to list all comments for a user's post.
http://[localhost:3000/api/users/6/posts/8/comments](http://localhost:3000/api/users/6/posts/8/comments)
image

Created an API endpoint to add a comment to a post. Remember that the owner of the comment is the user that makes it; it has been done by setting default current_user.
image

API endpoints receive JSON and respond JSON as well.

### CODE REVIEW

**Comment by Kamba56** [comment]
Hi @sajibarafatsiddiqui

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Kindly add proof that shows you were permitted by student success to work alone to your PR

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by sajibarafatsiddiqui** [comment]
image

**Comment by sajibarafatsiddiqui** [comment]
@Kamba56  Its a matter of great mockery that code reviewers cant see I am alone and not a part of any group. Every time I need to submit the proof. Also not asking me in slack before invalidating the review . I am raising the issue in student success so that at least future students can save their times in code review process

**Review by Reem-lab — APPROVED** [review]
# Hi @sajibarafatsiddiqui,  👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights
- [ ] Great job on the funtionality  💯
- [ ] Followed Gitflow 🔥
- [ ] No Linters error ✅


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
